# Generated by Django 5.0 on 2023-12-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('price', models.CharField(max_length=64, verbose_name='price')),
                ('image', models.CharField(max_length=64, verbose_name='image')),
                ('release_date', models.CharField(max_length=64, verbose_name='release_date')),
                ('lte_exists', models.CharField(max_length=64, verbose_name='lte_exists')),
                ('slug', models.CharField(max_length=64, verbose_name='slug')),
            ],
        ),
    ]
