# Generated by Django 5.0 on 2023-12-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
