# Generated by Django 5.0 on 2023-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер id')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('lte_exists', models.BooleanField(verbose_name='LTE')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
